FROM centos

LABEL "Name"="httpd"
LABEL "Author"="Prem"

MAINTAINER Prem Kumar Palanichamy

RUN yum install httpd -y
COPY index.html /var/www/html/

CMD [“/usr/sbin/httpd”,” -D”,” FOREGROUND”]
EXPOSE 80